PCA on the battery health prediction

In [32]:
# Imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

Creating the data frame and visualising the content

In [11]:
data = pd.read_csv("dataset/ev battery_failure prediction Dataset.csv")
data.head(10)

,vehicle_id,vehicle_brand,vehicle_model,vehicle_type,manufacturing_year,battery_manufacturer,battery_chemistry,battery_capacity_kwh,drive_type,odometer_km,...,sensor_fault_count,BMS_warning_count,abnormal_voltage_events,battery_stress_index,aging_score,thermal_health_score,charging_quality_score,driving_stress_score,predicted_remaining_life_cycles,battery_failure
0,EV100000,Ford,Mustang Mach-E,Truck,2022.0,Northvolt,NMC,NaN,AWD,290844.3,...,1.0,NaN,0.0,30.37,73.05,98.14,89.73,47.11,6748.0,0
1,EV100001,Tata,Tiago EV,Truck,2017.0,CATL,NCA,38.71,RWD,182239.5,...,0.0,1.0,0.0,67.94,82.50,NaN,NaN,55.38,5211.0,0
2,EV100002,Volkswagen,ID.3,Crossover,2016.0,BYD Battery,LFP,131.29,FWD,249369.3,...,0.0,1.0,0.0,74.84,90.33,60.02,86.84,74.54,4040.0,0
3,EV100003,NaN,Kona Electric,Sedan,2019.0,SK On,NMC,132.35,FWD,134830.2,...,NaN,0.0,0.0,46.94,56.69,66.43,93.93,31.69,NaN,0
4,EV100004,MG,ZS EV,SUV,2017.0,Guoxuan,LTO,25.72,AWD,158026.0,...,1.0,2.0,3.0,49.07,73.65,95.05,100.00,23.46,7290.0,0
5,EV100005,BYD,Atto 3,Sedan,2018.0,LG Energy Solution,LFP,104.54,FWD,189801.9,...,0.0,2.0,NaN,57.09,60.58,52.44,92.22,47.89,8738.0,0
6,EV100006,Tata,Tiago EV,Truck,2024.0,Panasonic,LMO,135.39,RWD,118449.0,...,0.0,0.0,1.0,41.52,33.03,83.06,89.99,65.86,8658.0,0
7,EV100007,Renault,Zoe,Sedan,2024.0,Panasonic,LMO,107.93,RWD,79443.2,...,0.0,3.0,1.0,48.63,30.21,69.13,91.85,55.21,9143.0,0
8,EV100008,Renault,Zoe,Hatchback,2015.0,Northvolt,NaN,81.71,AWD,251452.2,...,0.0,0.0,1.0,49.77,91.93,72.24,94.99,27.68,4427.0,1
9,EV100009,Ford,Mustang Mach-E,Crossover,2018.0,BYD Battery,NMC,69.85,RWD,253422.3,...,1.0,3.0,0.0,44.33,86.73,87.76,77.92,47.73,5897.0,0

In [12]:
data.describe()

,manufacturing_year,battery_capacity_kwh,odometer_km,vehicle_age_years,cycle_count,battery_health_percent,state_of_charge,depth_of_discharge,state_of_health,cell_voltage_avg,...,sensor_fault_count,BMS_warning_count,abnormal_voltage_events,battery_stress_index,aging_score,thermal_health_score,charging_quality_score,driving_stress_score,predicted_remaining_life_cycles,battery_failure
count,19018.000000,19310.000000,19134.000000,19232.000000,19234.000000,19102.000000,19036.000000,19168.000000,19044.000000,19060.000000,...,19032.000000,19094.000000,19240.000000,19270.000000,19164.000000,19368.00000,19282.000000,19320.000000,19102.000000,20000.0000
mean,2019.491482,87.124810,169562.067362,6.507302,1358.999584,81.911451,50.940556,44.429334,81.881542,3.597902,...,0.702449,1.206452,0.597401,47.380257,61.780447,80.64006,87.266611,40.446050,7825.358287,0.0692
std,2.864259,35.831323,74761.687034,2.882844,529.597491,8.991068,28.290460,17.035009,9.108197,0.126524,...,0.836291,1.090139,0.768265,12.722088,22.099914,15.29981,8.502523,13.266399,1680.547458,0.2538
min,2015.000000,25.000000,500.000000,1.370000,173.000000,47.030000,2.000000,5.230000,47.770000,3.061000,...,0.000000,0.000000,0.000000,2.850000,6.990000,18.00000,43.720000,0.000000,1656.000000,0.0000
25%,2017.000000,56.050000,116105.450000,4.000000,984.000000,75.970000,26.350000,31.440000,75.800000,3.513000,...,0.000000,0.000000,0.000000,38.550000,44.090000,73.11750,81.672500,31.117500,6635.250000,0.0000
50%,2019.000000,87.315000,158148.000000,6.520000,1295.000000,82.930000,50.760000,43.810000,82.880000,3.600000,...,1.000000,1.000000,0.000000,48.060000,61.985000,85.17000,87.935000,40.310000,7903.000000,0.0000
75%,2022.000000,118.300000,211502.900000,8.990000,1658.000000,88.820000,75.490000,56.962500,88.822500,3.687000,...,1.000000,2.000000,1.000000,56.380000,79.800000,91.60000,93.820000,49.652500,9086.000000,0.0000
max,2024.000000,149.010000,450000.000000,11.550000,3369.000000,99.800000,100.000000,90.340000,100.000000,3.850000,...,6.000000,7.000000,5.000000,93.620000,100.000000,100.00000,100.000000,88.700000,12870.000000,1.0000

Separate the qualitative and quantitatives data

In [34]:
# Separate battery_failure which is a boolean and not a quantitative value
data['battery_failure'] = data['battery_failure'].astype('category')

# Separate data
df_quanti = data.select_dtypes(include='number')
df_quali = data.select_dtypes(exclude='number')

# Fill the NaN in the data (necessary for the next steps)
df_quanti = df_quanti.fillna(df_quanti.median())

df_quanti.head(2)

,manufacturing_year,battery_capacity_kwh,odometer_km,vehicle_age_years,cycle_count,battery_health_percent,state_of_charge,depth_of_discharge,state_of_health,cell_voltage_avg,...,temperature_variance,sensor_fault_count,BMS_warning_count,abnormal_voltage_events,battery_stress_index,aging_score,thermal_health_score,charging_quality_score,driving_stress_score,predicted_remaining_life_cycles
0,2022.0,87.315,290844.3,4.45,1295.0,80.60,65.00,58.74,79.75,3.793,...,29.30,1.0,1.0,0.0,30.37,73.05,98.14,89.730,47.11,6748.0
1,2017.0,38.710,182239.5,9.17,1425.0,61.24,43.32,35.23,60.72,3.744,...,32.94,0.0,1.0,0.0,67.94,82.50,85.17,87.935,55.38,5211.0

Standardisation : Centering and scaling the quantitative data

In [28]:
stand_data = StandardScaler().fit_transform(df_quanti)
print(stand_data)

[[ 0.90613544  0.00521568  1.66451862 ...  0.29217031  0.51144855
  -0.65807975]
 [-0.8827723  -1.37533707  0.1800387  ...  0.07718011  1.14571883
  -1.59389307]
 [-1.24055385  1.25426016  1.09761177 ... -0.05396991  2.61520112
  -2.3068647 ]
 ...
 [-0.52499075 -1.7014094  -0.50256361 ... -0.73906404 -1.33153993
  -1.0970657 ]
 [-0.8827723   0.80463255 -0.68403258 ... -0.52587041 -0.6359134
  -1.19082969]
 [ 0.90613544 -0.04946108 -2.06479349 ... -0.12822836  0.97928999
   0.81291893]]

In [30]:
# Check that the means are 0 and the standard deviations are 1
print(np.mean(stand_data, axis=0))
print(np.std(stand_data, axis=0))

[ 3.69670516e-14  2.66453526e-17  1.15818466e-16  2.84217094e-18
  1.91491267e-16 -1.35287337e-15 -1.46371804e-16  3.09618997e-16
  8.71125394e-16  2.28546071e-15  8.45545856e-17  4.81747975e-16
  1.35180755e-16 -4.27213820e-17 -1.32871492e-16  1.57452718e-14
 -1.10134124e-16  1.62003744e-16  2.39452902e-16 -4.42312853e-17
 -5.93303184e-17 -1.27720057e-16 -1.59161573e-16  9.80548975e-17
  3.02247116e-16  1.10134124e-16 -1.88293825e-17  6.75015599e-17
 -3.84581256e-17  1.24344979e-17 -1.23634436e-16  1.46371804e-16
 -1.55964130e-16 -1.16173737e-16  2.79953838e-16  1.37490019e-16
  8.17124146e-18  9.27258270e-17  2.73558953e-17 -3.73745479e-16
 -8.45545856e-17  8.79296636e-17 -1.74438242e-16  2.03925765e-15
 -7.53175300e-17 -4.19220214e-17  1.40332190e-16  4.77839990e-17
  2.71782596e-17  6.43929354e-17  3.44613227e-17 -5.08038056e-17
  6.03961325e-17 -5.66657832e-16  2.41229259e-16 -4.57944793e-16
  5.39479572e-16  1.70530257e-16  2.77111667e-17]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Apply the PCA

In [33]:
# Instantiate the PCA (all components are kept by default)
acp = PCA()
# Run the PCA and get the factorial coordinates of the individuals in the matrix coord
coord = acp.fit_transform(stand_data)
print(coord)
# Number of computed components
n = acp.n_components_
print(n)

[[ 5.43286756e-01 -1.90397446e+00 -1.19027929e+00 ... -2.93949814e-02
   8.66843118e-02 -9.17990076e-01]
 [ 5.68709613e+00  1.00686466e+00 -1.98185633e+00 ...  6.56054170e-02
  -9.52139010e-03  2.33658288e-01]
 [ 6.54991586e+00  3.00031438e+00  1.34474447e+00 ...  4.99178837e-03
  -3.45893444e-01 -1.91118727e-01]
 ...
 [ 1.90138868e+00  1.52553613e+00 -2.84467929e+00 ...  1.07861044e-02
  -4.70701049e-02  8.86995264e-02]
 [ 3.30853575e+00 -2.69838783e+00 -1.04727146e+00 ...  5.44796332e-02
  -4.33290728e-02 -9.77593135e-02]
 [-2.02725506e+00  1.29966344e+00 -1.29030583e+00 ... -5.61848041e-02
   3.83222624e-02 -9.48759659e-03]]
59

Eigen value and inertia

In [35]:
# Get the eigenvalues / variances / inertia
# sklearn estimates the variance with n-1 degrees of freedom
variance = acp.explained_variance_
variance

array([8.77334854, 4.37502762, 3.48449814, 2.51531107, 2.33406154,
       2.17606187, 1.97672727, 1.90576624, 1.47529688, 1.3954823 ,
       1.30816599, 1.29509952, 1.27576446, 1.1135318 , 1.05779879,
       1.04717588, 1.03823697, 1.03062103, 1.02511111, 1.01588008,
       1.01292572, 1.00618927, 0.99962941, 0.99559669, 0.99242206,
       0.98889081, 0.98201559, 0.98162368, 0.97596716, 0.96661343,
       0.95588391, 0.94550315, 0.77995025, 0.72114015, 0.65173534,
       0.3919694 , 0.37651095, 0.2875102 , 0.28253947, 0.25592689,
       0.2404941 , 0.177387  , 0.1752224 , 0.15630946, 0.12088076,
       0.11286463, 0.1102424 , 0.08754446, 0.08224516, 0.07985107,
       0.07551593, 0.06694087, 0.06144941, 0.05755849, 0.05137412,
       0.0484894 , 0.04682636, 0.04362463, 0.03861891])

In [36]:
# An adjustment is needed to get the variance with n degrees of freedom (the usual convention in PCA)
eigval = variance * (len(stand_data) - 1) / len(stand_data)
print(eigval)

[8.77290987 4.37480887 3.48432392 2.5151853  2.33394484 2.17595307
 1.97662843 1.90567095 1.47522311 1.39541252 1.30810058 1.29503477
 1.27570068 1.11347612 1.0577459  1.04712352 1.03818506 1.0305695
 1.02505985 1.01582929 1.01287507 1.00613896 0.99957942 0.99554691
 0.99237244 0.98884136 0.98196649 0.98157459 0.97591836 0.9665651
 0.95583611 0.94545588 0.77991125 0.7211041  0.65170275 0.3919498
 0.37649213 0.28749582 0.28252534 0.2559141  0.24048207 0.17737813
 0.17521363 0.15630164 0.12087472 0.11285899 0.11023689 0.08754008
 0.08224104 0.07984708 0.07551216 0.06693752 0.06144634 0.05755561
 0.05137155 0.04848698 0.04682402 0.04362245 0.03861698]

In [39]:
# Check that the sum of the eigenvalues equals the number of variables
print("Number of variables: ", n)
print(np.sum(eigval, axis=0))

Number of variables:  59
59.00000000000002

In [40]:
# Share of each eigenvalue,
# i.e. percentage of inertia explained by each axis
np.set_printoptions(suppress=True)
print(acp.explained_variance_ratio_ * 100)

[14.86933877  7.41493028  5.90563376  4.26302594  3.9558387   3.68805605
  3.35021768  3.22995077  2.50037816  2.36510597  2.21711962  2.19497419
  2.16220454  1.88724766  1.79278966  1.77478563  1.7596357   1.74672797
  1.73738958  1.72174455  1.7167374   1.70532027  1.69420242  1.68736765
  1.68198718  1.67600231  1.66434999  1.66368575  1.65409891  1.63824593
  1.62006121  1.60246759  1.32188347  1.22221033  1.10458093  0.66432169
  0.63812225  0.48728106  0.47885651  0.43375271  0.40759673  0.3006409
  0.29697226  0.26491804  0.2048724   0.19128642  0.18684218  0.14837302
  0.1393916   0.13533403  0.12798671  0.11345343  0.10414633  0.09755189
  0.08707042  0.08218132  0.07936274  0.07393635  0.06545251]